substitutions:
  name: "heatmeister"
  friendly_name: "heatmeister"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "wildekek.heatmeister-esphome"
    version: "0.1.0"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://wildekek/heatmeister-esphome/heatmeister.yaml@v0.1.0
  import_full_config: false # or true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_key

# Enable OtA updates
ota:
  platform: esphome
  password: !secret ota_password

# Configure WiFi
wifi:
  min_auth_mode: WPA2
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: !secret wifi_fallback_password
captive_portal:

i2c:
  id: i2c_bus
  sda: 
    number: GPIO8
    ignore_strapping_warning: true
  scl: GPIO10
  scan: true
  frequency: 100kHz

ads1115:
  - address: 0x48

power_supply:
  # The 12v output for the fan
  - id: output_fan_power
    pin: GPIO5

output:
  # Green LED
  - platform: ledc
    id: output_led
    pin: GPIO6
  # Fan output
  - platform: ledc
    id: output_fan_pwm
    pin: 
      number: GPIO4
      inverted: True
    frequency: "25000Hz"
    min_power: 15% # Set this to the speed your fan needs to start spinning.
    max_power: 100% # Limit the maximum speed for the fan.
    power_supply: output_fan_power # This relay switches the power to the fan

light:
  - platform: monochromatic
    name: "LED"
    output: output_led

fan:
  - platform: speed
    output: output_fan_pwm
    id: fan_speed
    name: "Fan"
    restore_mode: RESTORE_DEFAULT_OFF

select:
  - platform: template
    id: control_strategy
    name: "Control strategy"
    icon: mdi:creation
    restore_value: True
    optimistic: true
    options:
      - manual
      - output
      - ΔT
    initial_option: manual

script:
  - id: update_fan_control
    then:
      - lambda: |-
          std::string strategy = id(control_strategy).current_option();
          
          // Manual mode: do nothing, respect user control
          if (strategy == "manual") {
            return;
          }
          
          float desired_speed = 0.0;  // Default to off
          
          if (strategy == "output") {
            // The 'output' strategy looks at a Home Assistant sensor that dictates 0-100%.
            // This can be useful with an OpenTherm boiler, coupling the fan to the amount
            // of heat output requested from the boiler.
            
            float output = id(requested_heat_output).state;
            if (!isnan(output) && output > 0.1) {
              desired_speed = output;
            }
          }
          else if (strategy == "ΔT") {
            // The 'ΔT' strategy optimizes for a high difference
            // between input and output temperature
            
            float delta_t = id(radiator_delta_t).state;
            float target_delta_t = 15.0;  // Optimal heat extraction
            float t_in_val = id(t_in).state;
            
            if (t_in_val >= 30.0 && delta_t >= 2.0) {
              // Increase fan if delta-T is low (poor extraction)
              // Decrease fan if delta-T is high (already extracting well)
              float speed_adjustment = (target_delta_t - delta_t) / target_delta_t;
              float base_speed = (t_in_val - 30.0) / 40.0;  // 30-70°C range
              desired_speed = base_speed * (1.0 + speed_adjustment * 0.5);
              desired_speed = clamp(desired_speed, 0.0f, 1.0f);
            }
          }
          
          // Single actuation point
          if (desired_speed <= 0.01) {
            auto call = id(fan_speed).turn_off();
            call.perform();
          } else {
            auto call = id(fan_speed).turn_on();
            call.set_speed(static_cast<int>(desired_speed * 100));
            call.perform();
          }

interval:
  - interval: 5s
    then:
      - script.execute: update_fan_control
      
binary_sensor:
  - platform: gpio
    name: "Button"
    pin: 
      number: GPIO3
      inverted: True
      mode:
        input: true
        pullup: true

sensor:
  # Read out the ADC voltages for the external temp sensors
  - platform: ads1115
    id: adc1_voltage
    multiplexer: 'A0_GND'
    gain: 6.144
    update_interval: 1s
    filters:
      - lambda: |-
          // Disconnected NTC detection
          if (x > 3.250 || x < 0.1) {
            return NAN;
          }
          return x;
  - platform: ads1115
    id: adc2_voltage
    multiplexer: 'A1_GND'
    gain: 6.144
    update_interval: 1s
    filters:
      - lambda: |-
          // Disconnected NTC detection
          if (x > 3.250 || x < 0.1) {
            return NAN;
          }
          return x;
  - platform: ads1115
    id: adc3_voltage
    multiplexer: 'A2_GND'
    gain: 6.144
    update_interval: 1s
    filters:
      - lambda: |-
          // Disconnected NTC detection
          if (x > 3.250 || x < 0.1) {
            return NAN;
          }
          return x;

  # ADC to NTC resistance
  - platform: resistance
    id: adc_1_resistance
    sensor: adc1_voltage
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: resistance
    id: adc_2_resistance
    sensor: adc2_voltage
    disabled_by_default: True
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: resistance
    id: adc_3_resistance
    sensor: adc3_voltage
    disabled_by_default: True
    configuration: DOWNSTREAM
    resistor: 10kOhm

  # NTC resistance to temperature sensor
  - platform: ntc
    sensor: adc_1_resistance
    id: "t_amb"
    name: "Temperature ambient"
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
  - platform: ntc
    sensor: adc_2_resistance
    id: "t_in"
    name: "Temperature in"
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
  - platform: ntc
    sensor: adc_3_resistance
    id: "t_out"
    name: "Temperature out"
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm

  # Read the internal temperature of the ESP32
  - platform: internal_temperature
    name: "Temperature internal"

  # Delta T between the input and output of the radiator
  - platform: template
    name: "Radiator Delta-T"
    id: radiator_delta_t
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    lambda: |-
      if (isnan(id(t_in).state) || isnan(id(t_out).state)) return {};
      return id(t_in).state - id(t_out).state;
    update_interval: 5s

  # Log the speed of the fan over time
  - platform: template
    id: fan_speed_sensor
    name: "Fan Speed"
    icon: "mdi:fan"
    unit_of_measurement: "%"
    state_class: "measurement"
    lambda: |-
      if (id(fan_speed).state) {
        return id(fan_speed).speed;
      } else {
        return 0.0;
      }
    update_interval: 10s

  # Import sensors from Home Assistant
  - platform: homeassistant
    entity_id: sensor.living_room_climate_temperature
    name: "Temperature room"
    disabled_by_default: True
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
  - platform: homeassistant
    entity_id: sensor.heating_controller_pid_heat_output
    id: requested_heat_output
    name: "Requested Heat Output"
    internal: False
    unit_of_measurement: "%"
    state_class: "measurement"

